pipeline{
    agent any
    stages{
        stage('Repositorio'){
            steps{
                echo 'Clonamos el repositorio'
                buildName '@BUILD_${BUILD_TIMESTAMP}_${BUILD_NUMBER}_PENDIENTE'
                git branch: 'desarrollo', url: 'https://github.com/ALICLEME/cursoJenkins.git'
            }
        }
        stage('Empaquetado'){
            steps{
                echo 'Lo hago con maven'
                sh 'cd miproyecto;mvn package'
            }
        }
        stage('Sonarqube'){
            steps{
                echo 'Llamo a sonar on maven'
                sh '''
                cd miproyecto

                mvn sonar:sonar \\
                  -Dsonar.projectKey=curso \\
                  -Dsonar.host.url=http://172.31.3.29:8081 \\
                  -Dsonar.login=607c3b69f0df2cef8224f167db1abd85ff3fec56
                '''
            }
        }
    }
    post{
        always{
            echo 'YO me ejecuto siempre'
        }
        success{
            echo 'YO me ejecuto cuando todo ha ido bien'
            junit 'miproyecto/target/surefire-reports/*.xml'
            buildName '@BUILD_${BUILD_TIMESTAMP}_${BUILD_NUMBER}_OK'
            archiveArtifacts artifacts: 'miproyecto/target/*.jar', followSymlinks: false
        }
        failure{
            echo 'YO me ejecuto cuando ha ido mal'
            buildName '@BUILD_${BUILD_TIMESTAMP}_${BUILD_NUMBER}_RUINA'
        }
        changed{
            echo 'YO me ejecuto si esta ejecucion no acaba en el mismo estado que la anterior'
        }
    }